# Generated by Django 3.0.2 on 2020-03-10 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('heure', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EXOModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('page', models.IntegerField()),
                ('test', models.CharField(blank=True, max_length=100)),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXO.programme')),
            ],
            options={
                'verbose_name': 'EXO',
                'ordering': ['nom'],
            },
        ),
    ]
