# Generated by Django 3.0.2 on 2020-01-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maison_co', '0002_auto_20200113_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
