# Generated by Django 3.0.2 on 2020-01-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_co', '0004_piece_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='surface',
            field=models.CharField(default=20, max_length=100),
        ),
    ]
