# Generated by Django 3.0.2 on 2020-01-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_co', '0005_auto_20200113_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
