# Generated by Django 3.0.2 on 2020-01-15 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maison_co', '0006_auto_20200113_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=1)),
                ('date_DN', models.DateTimeField(verbose_name='Date de naissance')),
                ('date_CR', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lumiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('obj_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=1)),
                ('date_DN', models.DateTimeField(verbose_name='Date de naissance')),
                ('date_CR', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'SuperUser',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=1)),
                ('date_DN', models.DateTimeField(verbose_name='Date de naissance')),
                ('date_CR', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Habitant',
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['name'], 'verbose_name': 'Pièce'},
        ),
        migrations.AlterField(
            model_name='piece',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
