# Generated by Django 3.0.2 on 2020-01-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maison_co', '0007_auto_20200115_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumiere',
            name='piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_co.Piece'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
