# Generated by Django 3.0.2 on 2020-01-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_co', '0009_auto_20200117_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperUser',
        ),
        migrations.RemoveField(
            model_name='lumiere',
            name='obj_id',
        ),
        migrations.AddField(
            model_name='admin',
            name='droit',
            field=models.CharField(choices=[(1, 'Administrateur'), (0, 'Utilisateur')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='droit',
            field=models.CharField(choices=[(1, 'Administrateur'), (0, 'Utilisateur')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='piece',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
