# Generated by Django 3.0.2 on 2020-01-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_co', '0010_auto_20200117_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumiere',
            name='categorie',
            field=models.CharField(choices=[('LUM', 'Lumière'), ('PRISE', 'Prise'), ('CAM', 'Camera')], default='Lumiere', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lumiere',
            name='etat',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0),
        ),
    ]
