# Generated by Django 3.0.2 on 2020-02-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maison_co', '0012_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
