# Generated by Django 3.0.2 on 2020-02-24 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maison_co', '0014_auto_20200224_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lumiere',
            name='fabricant',
            field=models.CharField(default='unknwon', max_length=100),
        ),
        migrations.AlterField(
            model_name='priseco',
            name='fabricant',
            field=models.CharField(default='unknwon', max_length=100),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fabricant', models.CharField(default='unknwon', max_length=100)),
                ('etat', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0)),
                ('categorie', models.CharField(choices=[('LUM', 'Lumière'), ('PRISE', 'Prise'), ('CAM', 'Camera')], max_length=100)),
                ('communication', models.CharField(choices=[('WF', 'WiFi'), ('BT', 'BlueTooth')], max_length=100, null=True)),
                ('piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_co.Piece')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
