# Generated by Django 3.0.2 on 2020-02-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maison_co', '0015_auto_20200224_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='categorie',
        ),
    ]
