# Generated by Django 3.0.2 on 2020-02-27 07:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maison_co', '0017_auto_20200224_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du scénario')),
                ('date_CR', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('action', models.CharField(choices=[('on', 'Allumer'), ('off', 'Eteindre')], default=0, max_length=100)),
                ('evenement', models.CharField(choices=[('mvt', 'Détecte un mouvement'), ('abs', 'Si je ne suis pas là'), ('h', 'A une heure précise')], default=0, max_length=100)),
                ('piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_co.Piece')),
            ],
            options={
                'verbose_name': 'Scénario',
                'ordering': ['name'],
            },
        ),
    ]
