# Generated by Django 3.0.2 on 2020-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_co', '0018_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='commentaire',
            field=models.CharField(default='a', max_length=100, verbose_name='Commentaire'),
            preserve_default=False,
        ),
    ]
